In [1]:
import numpy as np
import pandas as pd

In [5]:
# Need to find orange cap holder of season: means need to find batsman who hit most run in season
#Problem: we have matches dataset but it does not have batsman run and we have delivery dataset but it does not have season
match=pd.read_csv('matches.csv')
match.head(2)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [6]:
delivery=pd.read_csv('deliveries.csv')
delivery.head(2)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [8]:
# In both the data set we have one common thing id or match id we will merge both dataset based on that
new=delivery.merge(match,how='inner',left_on='match_id',right_on='id')

In [22]:
# We have done groupby on 2 things first on season and inside each season on batsman
season_wise_batsman=new.groupby(['season','batsman'])['batsman_runs'].sum().sort_values(ascending=False)
season_wise_batsman

season  batsman
2016    V Kohli       973
        DA Warner     848
2012    CH Gayle      733
2013    MEK Hussey    733
        CH Gayle      720
                     ...
2011    VR Aaron        0
2017    MM Patel        0
2011    ND Doshi        0
        S Nadeem        0
        SK Trivedi      0
Name: batsman_runs, Length: 1531, dtype: int64

In [23]:
type(season_wise_batsman)

pandas.Series

In [26]:
# Now we want to conver season_wise_batsman to data frame above series has 2 index one is season and other is batsman
#to convert it into data frame we will use rest_index function
season_wise_batsman_df=season_wise_batsman.reset_index()
season_wise_batsman_df

      season     batsman  batsman_runs
0       2016     V Kohli           973
1       2016   DA Warner           848
2       2012    CH Gayle           733
3       2013  MEK Hussey           733
4       2013    CH Gayle           720
...      ...         ...           ...
1526    2011    VR Aaron             0
1527    2017    MM Patel             0
1528    2011    ND Doshi             0
1529    2011    S Nadeem             0
1530    2011  SK Trivedi             0

[1531 rows x 3 columns]

In [31]:
# As we want to find orange cap holder from each season means only one batsman from each season who hit most of the run 
# so we will drop all remaining batsman of that season and keep only first one
top_batsman_data=season_wise_batsman_df.drop_duplicates(subset=['season'],keep='first').sort_values('season')
top_batsman_data

    season       batsman  batsman_runs
10    2008      SE Marsh           616
14    2009     ML Hayden           572
9     2010  SR Tendulkar           618
11    2011      CH Gayle           608
2     2012      CH Gayle           733
3     2013    MEK Hussey           733
6     2014    RV Uthappa           660
17    2015     DA Warner           562
0     2016       V Kohli           973
7     2017     DA Warner           641

In [32]:
#As we only want season and batsman name
top_batsman_data[['season','batsman']]

    season       batsman
10    2008      SE Marsh
14    2009     ML Hayden
9     2010  SR Tendulkar
11    2011      CH Gayle
2     2012      CH Gayle
3     2013    MEK Hussey
6     2014    RV Uthappa
17    2015     DA Warner
0     2016       V Kohli
7     2017     DA Warner